# Generated by Django 5.1.2 on 2025-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberModer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guessNumber', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
